.TH "//Pro03/github/KontrolerTC_H/KontrolerTC_Mega2560_v1/Cas_funkcije.h" 3 "Sat Apr 11 2015" "Kontroler TC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
//Pro03/github/KontrolerTC_H/KontrolerTC_Mega2560_v1/Cas_funkcije.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Funkcije"

.in +1c
.ti -1c
.RI "void \fBNarediTimeStr\fP (char *cas, unsigned long tcas, boolean izpSec)"
.br
.ti -1c
.RI "boolean \fBIsWeekend\fP (void)"
.br
.in -1c
.SH "Opis funkcije"
.PP 
.SS "boolean IsWeekend (void)"

.PP
Definirano v 22 vrstici datoteke Cas_funkcije\&.h\&.
.SS "void NarediTimeStr (char * cas, unsigned long tcas, boolean izpSec = \fCtrue\fP)"

.PP
Definirano v 12 vrstici datoteke Cas_funkcije\&.h\&.
.SH "Avtor"
.PP 
zgenerirano z Doxygen-om za Kontroler TC iz izvorne kode\&.
