.TH "//Pro03/github/KontrolerTC_H/KontrolerTC_Mega2560_v1/Encoder_butt.h" 3 "Sat Apr 11 2015" "Kontroler TC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
//Pro03/github/KontrolerTC_H/KontrolerTC_Mega2560_v1/Encoder_butt.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Arduino\&.h>\fP
.br

.SS "Funkcije"

.in +1c
.ti -1c
.RI "void \fBIzpisNaLCD\fP (void)"
.br
.ti -1c
.RI "static void \fBdoEncoderA\fP ()"
.br
.ti -1c
.RI "static void \fBdoEncoderB\fP ()"
.br
.ti -1c
.RI "void \fBEncoder_init\fP (void)"
.br
.ti -1c
.RI "static void \fBEncoder_check\fP (void)"
.br
.in -1c
.SS "Spremenljivke"

.in +1c
.ti -1c
.RI "volatile int \fBvirtualPosition\fP = 0"
.br
.ti -1c
.RI "boolean \fBA_set\fP = false"
.br
.ti -1c
.RI "boolean \fBB_set\fP = false"
.br
.ti -1c
.RI "boolean \fBrotating\fP =false"
.br
.in -1c
.SH "Opis funkcije"
.PP 
.SS "static void doEncoderA ()\fC [static]\fP"

.PP
Definirano v 51 vrstici datoteke Encoder_butt\&.h\&.
.SS "static void doEncoderB ()\fC [static]\fP"

.PP
Definirano v 65 vrstici datoteke Encoder_butt\&.h\&.
.SS "static void Encoder_check (void)\fC [static]\fP"

.PP
Definirano v 98 vrstici datoteke Encoder_butt\&.h\&.
.SS "void Encoder_init (void)"

.PP
Definirano v 81 vrstici datoteke Encoder_butt\&.h\&.
.SS "void IzpisNaLCD (void)"

.SH "Opis spremenljivke"
.PP 
.SS "boolean A_set = false"

.PP
Definirano v 46 vrstici datoteke Encoder_butt\&.h\&.
.SS "boolean B_set = false"

.PP
Definirano v 47 vrstici datoteke Encoder_butt\&.h\&.
.SS "boolean rotating =false"

.PP
Definirano v 48 vrstici datoteke Encoder_butt\&.h\&.
.SS "volatile int virtualPosition = 0"

.PP
Definirano v 20 vrstici datoteke Encoder_butt\&.h\&.
.SH "Avtor"
.PP 
zgenerirano z Doxygen-om za Kontroler TC iz izvorne kode\&.
