.TH "fl2byte4b" 3 "Sat Apr 11 2015" "Kontroler TC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fl2byte4b \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Configuration\&.h>\fP
.SS "Javni atributi"

.in +1c
.ti -1c
.RI "byte \fBby\fP [4]"
.br
.ti -1c
.RI "float \fBfval\fP"
.br
.in -1c
.SH "Podroben opis"
.PP 
Definirano v 184 vrstici datoteke Configuration\&.h\&.
.SH "Opis atributov"
.PP 
.SS "byte by[4]"

.PP
Definirano v 185 vrstici datoteke Configuration\&.h\&.
.SS "float fval"

.PP
Definirano v 186 vrstici datoteke Configuration\&.h\&.

.SH "Avtor"
.PP 
zgenerirano z Doxygen-om za Kontroler TC iz izvorne kode\&.
