.TH "ui2byte2" 3 "Sat Apr 11 2015" "Kontroler TC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ui2byte2 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Configuration\&.h>\fP
.SS "Javni atributi"

.in +1c
.ti -1c
.RI "byte \fBby\fP [2]"
.br
.ti -1c
.RI "unsigned int \fBuival\fP"
.br
.in -1c
.SH "Podroben opis"
.PP 
Definirano v 189 vrstici datoteke Configuration\&.h\&.
.SH "Opis atributov"
.PP 
.SS "byte by[2]"

.PP
Definirano v 190 vrstici datoteke Configuration\&.h\&.
.SS "unsigned int uival"

.PP
Definirano v 191 vrstici datoteke Configuration\&.h\&.

.SH "Avtor"
.PP 
zgenerirano z Doxygen-om za Kontroler TC iz izvorne kode\&.
