.TH "ul2byte4b" 3 "Sat Apr 11 2015" "Kontroler TC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ul2byte4b \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Configuration\&.h>\fP
.SS "Javni atributi"

.in +1c
.ti -1c
.RI "byte \fBby\fP [4]"
.br
.ti -1c
.RI "unsigned long \fBulval\fP"
.br
.in -1c
.SH "Podroben opis"
.PP 
Definirano v 179 vrstici datoteke Configuration\&.h\&.
.SH "Opis atributov"
.PP 
.SS "byte by[4]"

.PP
Definirano v 180 vrstici datoteke Configuration\&.h\&.
.SS "unsigned long ulval"

.PP
Definirano v 181 vrstici datoteke Configuration\&.h\&.

.SH "Avtor"
.PP 
zgenerirano z Doxygen-om za Kontroler TC iz izvorne kode\&.
