.TH "//Pro03/github/KontrolerTC_H/KontrolerTC_Mega2560_v1/Zapisi_sd.h" 3 "Sat Apr 11 2015" "Kontroler TC" \" -*- nroff -*-
.ad l
.nh
.SH NAME
//Pro03/github/KontrolerTC_H/KontrolerTC_Mega2560_v1/Zapisi_sd.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Funkcije"

.in +1c
.ti -1c
.RI "void \fBSDInit\fP (void)"
.br
.ti -1c
.RI "void \fBImeDatoteke\fP (char *ime)"
.br
.ti -1c
.RI "void \fBImeDatotekeOnOff\fP (char *ime)"
.br
.ti -1c
.RI "File \fBOdpriDatoteko\fP (char *imeDat, byte typeDat)"
.br
.ti -1c
.RI "void \fBPrintTempAllSDbin\fP (void)"
.br
.ti -1c
.RI "void \fBZapisiOnOffSD\fP (int state, byte tipSpremembe)"
.br
.ti -1c
.RI "void \fBIzpisDataOnOffSerial\fP (void)"
.br
.ti -1c
.RI "void \fBIzpisDatnaSerial\fP (void)"
.br
.in -1c
.SS "Spremenljivke"

.in +1c
.ti -1c
.RI "Sd2Card \fBcardSD\fP"
.br
.in -1c
.SH "Opis funkcije"
.PP 
.SS "void ImeDatoteke (char * ime)"

.PP
Definirano v 47 vrstici datoteke Zapisi_sd\&.h\&.
.SS "void ImeDatotekeOnOff (char * ime)"

.PP
Definirano v 55 vrstici datoteke Zapisi_sd\&.h\&.
.SS "void IzpisDataOnOffSerial (void)"

.PP
Definirano v 372 vrstici datoteke Zapisi_sd\&.h\&.
.SS "void IzpisDatnaSerial (void)"

.PP
Definirano v 401 vrstici datoteke Zapisi_sd\&.h\&.
.SS "File OdpriDatoteko (char * imeDat, byte typeDat)"

.PP
Definirano v 61 vrstici datoteke Zapisi_sd\&.h\&.
.SS "void PrintTempAllSDbin (void)"

.PP
Definirano v 94 vrstici datoteke Zapisi_sd\&.h\&.
.SS "void SDInit (void)"

.PP
Definirano v 22 vrstici datoteke Zapisi_sd\&.h\&.
.SS "void ZapisiOnOffSD (int state, byte tipSpremembe = \fC0\fP)"

.PP
Definirano v 198 vrstici datoteke Zapisi_sd\&.h\&.
.SH "Opis spremenljivke"
.PP 
.SS "Sd2Card cardSD"

.PP
Definirano v 17 vrstici datoteke Zapisi_sd\&.h\&.
.SH "Avtor"
.PP 
zgenerirano z Doxygen-om za Kontroler TC iz izvorne kode\&.
